if(EXISTS "/home/alexander-vegazo/Documents/repos/halo/build-dev/tests/unit/api/test_api[1]_tests.cmake")
  include("/home/alexander-vegazo/Documents/repos/halo/build-dev/tests/unit/api/test_api[1]_tests.cmake")
else()
  add_test(test_api_NOT_BUILT test_api_NOT_BUILT)
endif()
