if(EXISTS "/home/alexander-vegazo/Documents/repos/halo/build-m2/tests/unit/state/test_state[1]_tests.cmake")
  include("/home/alexander-vegazo/Documents/repos/halo/build-m2/tests/unit/state/test_state[1]_tests.cmake")
else()
  add_test(test_state_NOT_BUILT test_state_NOT_BUILT)
endif()
