foreach(be IN ITEMS cpu)
  if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/${be}/CMakeLists.txt)
    add_subdirectory(${be})
  endif()
endforeach()
if(HALO_BUILD_VULKAN AND EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/vulkan/CMakeLists.txt)
  add_subdirectory(vulkan)
endif()
if(HALO_BUILD_HIP AND EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/hip/CMakeLists.txt)
  add_subdirectory(hip)
endif()
