if(EXISTS "/home/alexander-vegazo/Documents/repos/halo/build-dev/tests/unit/runtime/test_runtime[1]_tests.cmake")
  include("/home/alexander-vegazo/Documents/repos/halo/build-dev/tests/unit/runtime/test_runtime[1]_tests.cmake")
else()
  add_test(test_runtime_NOT_BUILT test_runtime_NOT_BUILT)
endif()
