if(EXISTS "/home/alexander-vegazo/Documents/repos/halo/build-dev/tests/unit/kv_cache/test_kv_cache[1]_tests.cmake")
  include("/home/alexander-vegazo/Documents/repos/halo/build-dev/tests/unit/kv_cache/test_kv_cache[1]_tests.cmake")
else()
  add_test(test_kv_cache_NOT_BUILT test_kv_cache_NOT_BUILT)
endif()
