if(EXISTS "/home/alexander-vegazo/Documents/repos/halo/build-m2/tests/unit/tokenizer/test_tokenizer[1]_tests.cmake")
  include("/home/alexander-vegazo/Documents/repos/halo/build-m2/tests/unit/tokenizer/test_tokenizer[1]_tests.cmake")
else()
  add_test(test_tokenizer_NOT_BUILT test_tokenizer_NOT_BUILT)
endif()
