if(EXISTS "/home/alexander-vegazo/Documents/repos/halo/build-m2/tests/unit/backend/test_hip_forward[1]_tests.cmake")
  include("/home/alexander-vegazo/Documents/repos/halo/build-m2/tests/unit/backend/test_hip_forward[1]_tests.cmake")
else()
  add_test(test_hip_forward_NOT_BUILT test_hip_forward_NOT_BUILT)
endif()
