if(EXISTS "/home/alexander-vegazo/Documents/repos/halo/build-dev/tests/unit/autotune/test_autotune[1]_tests.cmake")
  include("/home/alexander-vegazo/Documents/repos/halo/build-dev/tests/unit/autotune/test_autotune[1]_tests.cmake")
else()
  add_test(test_autotune_NOT_BUILT test_autotune_NOT_BUILT)
endif()
