#pragma once
// Internal Unicode support for the tokenizer: UTF-8 decoding with U+FFFD substitution,
// the character classes used by the qwen35 pre-tokenizer regex, and NFC normalization.
//
// Tables come from src/tokenizer/unicode_data.inc, generated by
// `python/tools/make_tokenizer_golden.py tables`, which probes HF tokenizers (the
// reference) per codepoint instead of assuming one Unicode version.

#include <cstddef>
#include <cstdint>
#include <string>
#include <string_view>
#include <vector>

namespace halo::tokenizer::unicode {

inline constexpr char32_t kReplacement = 0xFFFD;

/// Character class as seen by the qwen35 Split regex.
enum class CpClass : std::uint8_t {
    Other = 0,       ///< [^\s\p{L}\p{M}\p{N}]
    LetterMark = 1,  ///< [\p{L}\p{M}]
    Number = 2,      ///< \p{N}
    Space = 3,       ///< \s (Oniguruma White_Space, includes CR and LF)
};

[[nodiscard]] CpClass classify(char32_t cp) noexcept;

/// Case-fold sets of the `(?i:'s|'t|'re|'ve|'m|'ll|'d)` alternative (probed from HF).
[[nodiscard]] bool fold_single(char32_t cp) noexcept;     ///< s t m d (and fold variants)
[[nodiscard]] bool fold_re_ve_first(char32_t cp) noexcept; ///< r v
[[nodiscard]] bool fold_e_second(char32_t cp) noexcept;    ///< e
[[nodiscard]] bool fold_l_first(char32_t cp) noexcept;     ///< first l of 'll
[[nodiscard]] bool fold_l_second(char32_t cp) noexcept;    ///< second l of 'll

/// Result of decoding one UTF-8 sequence starting at a given byte.
struct Utf8Step {
    enum class Status : std::uint8_t { Ok, Invalid, Incomplete };
    Status status;
    char32_t cp;       ///< valid only when status == Ok
    std::size_t len;   ///< bytes consumed: the sequence (Ok) or its maximal subpart (else)
};

/// Decodes one sequence at `s[i]` (i < s.size()). Invalid = the maximal subpart of an
/// ill-formed sequence (Unicode §3.9, Table 3-7); Incomplete = a well-formed prefix cut off
/// by the end of `s`.
[[nodiscard]] Utf8Step decode_step(std::string_view s, std::size_t i) noexcept;

[[nodiscard]] bool is_valid_utf8(std::string_view s) noexcept;

/// Appends the UTF-8 encoding of `cp` (must be a scalar value).
void append_utf8(std::string& out, char32_t cp);

/// Lossy conversion to valid UTF-8: each ill-formed maximal subpart (including an
/// incomplete tail) becomes U+FFFD. Matches Python's `bytes.decode('utf-8', 'replace')`
/// and Rust's `String::from_utf8_lossy`.
[[nodiscard]] std::string to_valid_utf8(std::string_view s);

/// A codepoint plus the byte offset (in the caller's original text) it came from.
struct CpOff {
    char32_t cp;
    std::uint32_t off;
};

/// True when NFC is guaranteed to leave the (valid UTF-8) text unchanged. Conservative:
/// false means "may change", and the caller runs `nfc`.
[[nodiscard]] bool nfc_quick_check(std::string_view valid_utf8) noexcept;

/// NFC in place over codepoints. Offsets stay non-decreasing: decomposed parts inherit
/// their source offset, a reordered mark run takes the run's smallest offset, and a
/// composite keeps its starter's offset.
void nfc(std::vector<CpOff>& cps);

/// NFC of a valid UTF-8 string (convenience for tests and callers without offsets).
[[nodiscard]] std::string nfc_utf8(std::string_view valid_utf8);

}  // namespace halo::tokenizer::unicode
