#include "metrics.h"

#include <format>

namespace halo::api {

void Histogram::observe(double seconds) {
    std::lock_guard lk(mu_);
    for (std::size_t i = 0; i < kBounds.size(); ++i) {
        if (seconds <= kBounds[i]) ++buckets_[i];
    }
    ++count_;
    sum_ += seconds;
}

void Histogram::render(std::string& out, const std::string& name, const std::string& help) const {
    std::lock_guard lk(mu_);
    out += std::format("# HELP {} {}\n# TYPE {} histogram\n", name, help, name);
    for (std::size_t i = 0; i < kBounds.size(); ++i) {
        out += std::format("{}_bucket{{le=\"{}\"}} {}\n", name, kBounds[i], buckets_[i]);
    }
    out += std::format("{}_bucket{{le=\"+Inf\"}} {}\n{}_sum {}\n{}_count {}\n", name, count_, name, sum_, name, count_);
}

void Metrics::count_request(const std::string& route, int status) {
    std::lock_guard lk(mu_);
    ++requests_[{route, status}];
}

void Metrics::count_rejection(const std::string& reason) {
    std::lock_guard lk(mu_);
    ++rejections_[reason];
}

namespace {

void metric(std::string& out, std::string_view name, std::string_view type, std::string_view help, auto value) {
    out += std::format("# HELP {} {}\n# TYPE {} {}\n{} {}\n", name, help, name, type, name, value);
}

double ratio(std::uint64_t num, std::uint64_t den) {
    return den == 0 ? 0.0 : static_cast<double>(num) / static_cast<double>(den);
}

}  // namespace

std::string Metrics::render(const runtime::EngineStats& e, std::size_t queued, std::size_t admitted) const {
    std::string out;
    {
        std::lock_guard lk(mu_);
        out += "# HELP halo_api_requests_total HTTP requests by route and status.\n# TYPE halo_api_requests_total counter\n";
        for (const auto& [k, v] : requests_) {
            out += std::format("halo_api_requests_total{{route=\"{}\",status=\"{}\"}} {}\n", k.first, k.second, v);
        }
        out += "# HELP halo_api_rejections_total Requests refused by admission control or limits.\n"
               "# TYPE halo_api_rejections_total counter\n";
        for (const auto& [k, v] : rejections_) out += std::format("halo_api_rejections_total{{reason=\"{}\"}} {}\n", k, v);
    }
    metric(out, "halo_api_active_requests", "gauge", "Generation requests currently holding a slot.", admitted);
    metric(out, "halo_api_queued_requests", "gauge", "Generation requests waiting for a slot.", queued);
    metric(out, "halo_api_prompt_tokens_total", "counter", "Prompt tokens submitted.", prompt_tokens.load());
    metric(out, "halo_api_completion_tokens_total", "counter", "Tokens generated (reasoning + output).", completion_tokens.load());
    metric(out, "halo_api_reasoning_tokens_total", "counter", "Generated tokens inside think blocks.", reasoning_tokens.load());
    metric(out, "halo_api_cancelled_total", "counter", "Generations cancelled by client disconnect or shutdown.", cancelled.load());
    metric(out, "halo_api_reasoning_budget_closes_total", "counter", "Think blocks closed early by the reasoning budget.",
           budget_closes.load());
    metric(out, "halo_api_last_decode_tokens_per_second", "gauge", "Decode rate reported for the last finished request.",
           last_decode_tps.load());
    ttft.render(out, "halo_api_time_to_first_token_seconds", "Time from submission to the first generated token.");
    duration.render(out, "halo_api_generation_duration_seconds", "End-to-end generation latency.");

    metric(out, "halo_engine_active_sequences", "gauge", "Sequences the engine is running.", e.active_sequences);
    metric(out, "halo_engine_queued_requests", "gauge", "Requests queued inside the engine.", e.queued_requests);
    metric(out, "halo_engine_tokens_generated_total", "counter", "Tokens generated by the engine.", e.tokens_generated);
    metric(out, "halo_engine_prefix_cache_hits_total", "counter", "Prefix-cache hits.", e.prefix_cache_hits);
    metric(out, "halo_engine_prefix_cache_misses_total", "counter", "Prefix-cache misses.", e.prefix_cache_misses);
    metric(out, "halo_engine_prefix_cache_hit_ratio", "gauge", "hits / (hits + misses) since start.",
           ratio(e.prefix_cache_hits, e.prefix_cache_hits + e.prefix_cache_misses));
    metric(out, "halo_engine_speculative_attempts_total", "counter", "MTP draft tokens proposed.", e.speculative_attempts);
    metric(out, "halo_engine_speculative_accepts_total", "counter", "MTP draft tokens accepted.", e.speculative_accepts);
    metric(out, "halo_engine_speculative_acceptance_ratio", "gauge", "accepts / attempts since start.",
           ratio(e.speculative_accepts, e.speculative_attempts));
    return out;
}

}  // namespace halo::api
