if(EXISTS "/home/alexander-vegazo/Documents/repos/halo/build-dev/tests/unit/memory/test_memory_fixtures[1]_tests.cmake")
  include("/home/alexander-vegazo/Documents/repos/halo/build-dev/tests/unit/memory/test_memory_fixtures[1]_tests.cmake")
else()
  add_test(test_memory_fixtures_NOT_BUILT test_memory_fixtures_NOT_BUILT)
endif()
