if(EXISTS "/home/alexander-vegazo/Documents/repos/halo/build-m2/tests/unit/template/test_template[1]_tests.cmake")
  include("/home/alexander-vegazo/Documents/repos/halo/build-m2/tests/unit/template/test_template[1]_tests.cmake")
else()
  add_test(test_template_NOT_BUILT test_template_NOT_BUILT)
endif()
