if(EXISTS "/home/alexander-vegazo/Documents/repos/halo/build-m2/tests/unit/vulkan/test_vulkan_kv[1]_tests.cmake")
  include("/home/alexander-vegazo/Documents/repos/halo/build-m2/tests/unit/vulkan/test_vulkan_kv[1]_tests.cmake")
else()
  add_test(test_vulkan_kv_NOT_BUILT test_vulkan_kv_NOT_BUILT)
endif()
