if(EXISTS "/home/alexander-vegazo/Documents/repos/halo/build-m2/tests/unit/sampling/test_sampling[1]_tests.cmake")
  include("/home/alexander-vegazo/Documents/repos/halo/build-m2/tests/unit/sampling/test_sampling[1]_tests.cmake")
else()
  add_test(test_sampling_NOT_BUILT test_sampling_NOT_BUILT)
endif()
