if(EXISTS "/home/alexander-vegazo/Documents/repos/halo/build-m2/tests/unit/memory/test_memory[1]_tests.cmake")
  include("/home/alexander-vegazo/Documents/repos/halo/build-m2/tests/unit/memory/test_memory[1]_tests.cmake")
else()
  add_test(test_memory_NOT_BUILT test_memory_NOT_BUILT)
endif()
