if(EXISTS "/home/alexander-vegazo/Documents/repos/halo/build-m2/tests/unit/cli/test_cli[1]_tests.cmake")
  include("/home/alexander-vegazo/Documents/repos/halo/build-m2/tests/unit/cli/test_cli[1]_tests.cmake")
else()
  add_test(test_cli_NOT_BUILT test_cli_NOT_BUILT)
endif()
