# Embed one SPIR-V binary into a C++ source file (TRD §41: "embed SPIR-V with hashes for
# cache validation"). Invoked at build time as
#   cmake -DSPV=<file.spv> -DID=<c identifier> -DNAME=<shader name> -DSOURCE=<rel path>
#         -DOUT=<file.cpp> -P embed_spirv.cmake
# The output depends only on the SPIR-V bytes and the relative source path, never on
# absolute paths or time, so it is reproducible.
foreach(v SPV ID NAME SOURCE OUT)
  if(NOT DEFINED ${v})
    message(FATAL_ERROR "embed_spirv.cmake: ${v} not set")
  endif()
endforeach()

file(READ "${SPV}" hex HEX)
file(SHA256 "${SPV}" sha)
string(LENGTH "${hex}" nhex)
math(EXPR nbytes "${nhex} / 2")
math(EXPR rem "${nbytes} % 4")
if(nbytes EQUAL 0 OR NOT rem EQUAL 0)
  message(FATAL_ERROR "embed_spirv.cmake: ${SPV} is ${nbytes} bytes (not a whole number of SPIR-V words)")
endif()
math(EXPR nwords "${nbytes} / 4")

# SPIR-V is a stream of little-endian 32-bit words: bytes b0 b1 b2 b3 -> 0xb3b2b1b0.
string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," words "${hex}")
# Break lines every 8 words to keep the generated file readable.
string(REGEX REPLACE "((0x[0-9a-f]+u,){8})" "\\1\n    " words "${words}")

file(WRITE "${OUT}.tmp"
"// GENERATED by backends/vulkan/cmake/embed_spirv.cmake from ${SOURCE} — do not edit.
#include \"shader_registry.h\"

namespace halo::vulkan::detail {
namespace {
constexpr std::uint32_t k_words[${nwords}] = {
    ${words}
};
}  // namespace

extern constinit const EmbeddedShader ${ID};
constinit const EmbeddedShader ${ID}{
    \"${NAME}\", \"${SOURCE}\", std::span<const std::uint32_t>(k_words), \"${sha}\"};
}  // namespace halo::vulkan::detail
")
# Only touch the output when the content changed (keeps incremental builds minimal).
file(COPY_FILE "${OUT}.tmp" "${OUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUT}.tmp")
