if(EXISTS "/home/alexander-vegazo/Documents/repos/halo/build-dev/tests/unit/cpu_kernels/test_cpu_thread_pool[1]_tests.cmake")
  include("/home/alexander-vegazo/Documents/repos/halo/build-dev/tests/unit/cpu_kernels/test_cpu_thread_pool[1]_tests.cmake")
else()
  add_test(test_cpu_thread_pool_NOT_BUILT test_cpu_thread_pool_NOT_BUILT)
endif()
