if(EXISTS "/home/alexander-vegazo/Documents/repos/halo/build-dev/tests/unit/models/test_models[1]_tests.cmake")
  include("/home/alexander-vegazo/Documents/repos/halo/build-dev/tests/unit/models/test_models[1]_tests.cmake")
else()
  add_test(test_models_NOT_BUILT test_models_NOT_BUILT)
endif()
