if(EXISTS "/home/alexander-vegazo/Documents/repos/halo/build-dev/tests/test_core[1]_tests.cmake")
  include("/home/alexander-vegazo/Documents/repos/halo/build-dev/tests/test_core[1]_tests.cmake")
else()
  add_test(test_core_NOT_BUILT test_core_NOT_BUILT)
endif()
